<a href="https://colab.research.google.com/github/Roger-trindade/caixa_rapido/blob/main/Aprendizado_supervisionado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

dontpad.com/710DS-0308

In [ ]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

# Modelo ótimo

## Carregamento dos dados

In [ ]:
data = {
    'Marketing' : [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    'Vendas' : [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
}
df = pd.DataFrame(data)
df

Marketing  Vendas
0        100      50
1        200     100
2        300     150
3        400     200
4        500     250
5        600     300
6        700     350
7        800     400
8        900     450
9       1000     500

Espera-se que a função seja do tipo y = 0.5 * x

## Separação X e Y

In [ ]:
X = df[['Marketing']]
y = df['Vendas']

In [ ]:
X

Marketing
0        100
1        200
2        300
3        400
4        500
5        600
6        700
7        800
8        900
9       1000

In [ ]:
y

0     50
1    100
2    150
3    200
4    250
5    300
6    350
7    400
8    450
9    500
Name: Vendas, dtype: int64

## Separação treino e teste

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 93)

In [ ]:
X_treino

Marketing
6        700
7        800
9       1000
1        200
0        100
4        500
5        600

In [ ]:
X_teste

Marketing
2        300
8        900
3        400

## Criar o modelo

In [ ]:
modelo = LinearRegression()

In [ ]:
modelo

LinearRegression()

In [ ]:
modelo.fit(X_treino, y_treino)

LinearRegression()

In [ ]:
modelo.coef_

array([0.5])

In [ ]:
modelo.intercept_ # É o mesmo de -0.00000000000001 e é praticamente 0

-1.1368683772161603e-13

In [ ]:
previsao = modelo.predict(X_teste)
previsao

array([150., 450., 200.])

In [ ]:
X_teste

Marketing
2        300
8        900
3        400

## Calculando erro do modelo

In [ ]:
mse = mean_squared_error(y_teste, previsao)
mse

5.6545549686242126e-27

# Modelo não-ótimo

In [ ]:
data = {
    'Marketing' : [110, 190, 310, 390, 510, 590, 710, 790, 910, 990],
    'Vendas' : [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
}
df = pd.DataFrame(data)
df

Marketing  Vendas
0        110      50
1        190     100
2        310     150
3        390     200
4        510     250
5        590     300
6        710     350
7        790     400
8        910     450
9        990     500

## Separaçao X e Y

In [ ]:
X = df[['Marketing']]
y = df['Vendas']

In [ ]:
X

Marketing
0        110
1        190
2        310
3        390
4        510
5        590
6        710
7        790
8        910
9        990

In [ ]:
y

0     50
1    100
2    150
3    200
4    250
5    300
6    350
7    400
8    450
9    500
Name: Vendas, dtype: int64

## Separaçao treino e teste

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 93)

In [ ]:
X_treino

Marketing
6        710
7        790
9        990
1        190
0        110
4        510
5        590

In [ ]:
X_teste

Marketing
2        310
8        910
3        390

## Criar modelo

In [ ]:
modelo = LinearRegression()

In [ ]:
modelo

LinearRegression()

In [ ]:
modelo.fit(X_treino, y_treino)

LinearRegression()

In [ ]:
modelo.coef_

array([0.50559136])

In [ ]:
modelo.intercept_

-2.392911296436637

In [ ]:
previsao = modelo.predict(X_teste)
previsao

array([154.3404094 , 457.69522365, 194.78771797])

In [ ]:
X_teste

Marketing
2        310
8        910
3        390

## calculando erro do modelo

In [ ]:
mse = mean_squared_error(y_teste, previsao)
mse

35.074501612577905

# modelo - Classificador

## Carregamento de dados

In [ ]:
df = pd.DataFrame({
    'Idade' : [25, 35, 45, 20, 30, 50, 40, 55, 60, 70],
    'Renda' : [3000, 4000, 5000, 2000, 3500, 6000, 5500, 7000, 8000, 9000],
    'Compra' : [0,0,1,0,1,1,1,1,1,1]
})
df

Idade  Renda  Compra
0     25   3000       0
1     35   4000       0
2     45   5000       1
3     20   2000       0
4     30   3500       1
5     50   6000       1
6     40   5500       1
7     55   7000       1
8     60   8000       1
9     70   9000       1

In [ ]:
X = df[['Idade', 'Renda']]
y = df['Compra']

In [ ]:
X

Idade  Renda
0     25   3000
1     35   4000
2     45   5000
3     20   2000
4     30   3500
5     50   6000
6     40   5500
7     55   7000
8     60   8000
9     70   9000

## Separaçao treino teste

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 93)

In [ ]:
X_treino

Idade  Renda
6     40   5500
7     55   7000
9     70   9000
1     35   4000
0     25   3000
4     30   3500
5     50   6000

## Criando o modelo

In [ ]:
modelo_logistico = LogisticRegression()
modelo_logistico

LogisticRegression()

In [ ]:
modelo_logistico.fit(X_treino, y_treino)

LogisticRegression()

In [ ]:
modelo_logistico.coef_

array([[-0.594672  ,  0.00515452]])

In [ ]:
modelo_logistico.intercept_

array([-0.10056524])

In [ ]:
previsao_logistica = modelo_logistico.predict(X_teste)
previsao_logistica

array([0, 1, 0])

In [ ]:
X_teste

Idade  Renda
2     45   5000
8     60   8000
3     20   2000

## Calcula acurácia

In [ ]:
acuracia = accuracy_score(y_teste, previsao_logistica)
acuracia

0.6666666666666666